name: PinboardLog
options:
  bundleIdPrefix: com.shimondeitel.pinboardlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  PinboardLog:
    type: application
    platform: iOS
    sources:
      - path: PinboardLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pinboardlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: PinboardLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  PinboardLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PinboardLogTests
      - path: PinboardLog.storekit
    dependencies:
      - target: PinboardLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pinboardlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  PinboardLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: PinboardLogUITests
    dependencies:
      - target: PinboardLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.pinboardlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  PinboardLog:
    build:
      targets:
        PinboardLog: all
        PinboardLogTests: [test]
        PinboardLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: PinboardLog.storekit
    test:
      config: Debug
      storeKitConfiguration: PinboardLog.storekit
      targets:
        - PinboardLogTests
        - PinboardLogUITests
    archive:
      config: Release
